export const catalogo = [
    { 
        id: "1", 
        marca: 'Instituto Recriar', 
        nome: 'Medalha de São Bento Frente',
        preco: 50, 
        imagem: 'product-01.jpeg', 
        feminino: false,
    }, 
    { 
        id: "2", 
        marca: 'Instituto Recriar', 
        nome: 'Medalha de São Bento Verso', 
        preco: 50, 
        imagem: 'product-02.jpeg', 
        feminino: false,
    }, 
    { 
        id: "3", 
        marca: 'Instituto Recriar', 
        nome: 'Nossa Senhora', 
        preco: 150, 
        imagem: 'product-03.jpeg', 
        feminino: false,
    }, 
    { 
        id: "4", 
        marca: 'Instituto Recriar', 
        nome: 'Escultura de Nosso Senhor', 
        preco: 300, 
        imagem: 'product-04.jpeg', 
        feminino: false, 
    },
    { 
        id: "5", 
        marca: 'Instituto Recriar', 
        nome: 'Cruz de Nosso Senhor', 
        preco: 300, 
        imagem: 'product-05.jpeg', 
        feminino: false, 
    },
    { 
        id: "6", 
        marca: 'Instituto Recriar', 
        nome: 'Abajur de Garrafa', 
        preco: 30, 
        imagem: 'product-06.jpeg', 
        feminino: true, 
    },
    { 
        id: "7", 
        marca: 'Instituto Recriar', 
        nome: 'Medalhas de São Bento', 
        preco: 100, 
        imagem: 'product-07.jpeg', 
        feminino: true, 
    }, 
    { 
        id: "8", 
        marca: 'Instituto Recriar', 
        nome: 'Cruz', 
        preco: 150, 
        imagem: 'product-08.jpeg', 
        feminino: true,
    },
];